# Generated by Codex on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="lead",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
