# Generated by Codex on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_lead_delivery_tracking"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["sent_at"], name="lead_sent_at_idx"),
        ),
    ]
