# Generated by Django 6.0.3 on 2026-03-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lead_sent_at_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_sent_at_idx',
        ),
    ]
